import type { NextPage } from "next";

const About: NextPage = () => {
  return (
    <div>
      <p>
        Incense Hermitage was developed by Sam Moss. It is written in Ruby on
        Rails and Next.js.{" "}
        <p>
          Radar charts are built with d3.js using code adopted from{" "}
          <a href="https://yangdanny97.github.io/blog/2019/03/01/D3-Spider-Chart">
            Danny Yang
          </a>
        </p>
      </p>
      <p>
        Kanji generated by{" "}
        <a href="https://fontmeme.com/japanese/">Font Meme</a>
      </p>
    </div>
  );
};

export default About;
