source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1.4', '>= 6.1.4.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'
# Use Puma as the app server
gem 'puma', '~> 5.0'

gem 'bootsnap', '>= 1.4.4', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'

gem 'active_model_serializers'
gem 'aasm', '~>5.2'
gem 'sentry-ruby', '~>4.7'

# stats command
gem 'simple_command', '~> 0.1.0'
# This may need to be temporarily removed during db setup
gem 'descriptive_statistics', '~>2.5'

# auth
# Clearance versions >= 2.2.1 don't send cookies,
# so we need this old version until https://github.com/thoughtbot/clearance/issues/938
# is fixed.
gem 'clearance', '2.2.1'
gem 'cancancan', '~>3.3'

gem 'friendly_id', '~> 5.4.0'

gem 'faker'

gem 'kaminari'

gem 'countries'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  gem 'rspec-rails', '~>5.0'
  gem 'factory_bot_rails', '~>6.2'
  gem 'vcr', '~>6.0'
  gem 'webmock', '~>3.14'
  gem 'letter_opener_web', '~>1.4'
end

group :development do
  gem 'listen', '~> 3.3'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'annotate'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
